#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT="$(cd $HERE/.. && pwd)"
CLASSICO="$ROOT/classico"
. $CLASSICO/shibumi/defs

DEVKA="$ROOT"
DEVKA_USER="$HOME/.devka-user"

# [[ $NOP == 1 ]] && OP=echo


OSNICK="${OSNICK:-noble}"
BOX_IMAGE_VER="${BOX_VER:-1}"
[[ -z $BOX_IMAGE ]] && BOX_IMAGE="devka/devbox:${OSNICK}.${BOX_IMAGE_VER}"

HOST_USER="$(id -un)"

BOX_ID="${BOX_ID:-1}"
BOX_NAME="${HOST_USER}-devbox${BOX_ID}"
BOX_DNAME="$BOX_NAME"
# BOX_DNAME="${HOST_USER}/devbox${BOX_ID}:${OSNICK}.${BOX_IMAGE_VER}"

var_run=$HOME/.local/var/run

#----------------------------------------------------------------------------------------------

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"
HOST_GROUP="$(id -gn)"
GIT_USER_NAME="$(git config --global user.name)"
GIT_EMAIL="$(git config --global user.email)"

RAM=8g

#----------------------------------------------------------------------------------------------

catch() {
	docker stop $DBOX_NAME > /dev/null
	rm -f $var_run/$BOX_NAME.cid
	exit 1
}

#----------------------------------------------------------------------------------------------

if ! docker ps -f name=$BOX_NAME | grep -q "$BOX_NAME"; then
	if [[ -z $_Dbg_DEBUGGER_LEVEL ]]; then
		trap catch ERR
	fi
	echo "# Starting box $DBOX_NAME ..."
	mkdir -p $var_run
	$OP rm -f $var_run/$BOX_NAME.cid
	#	--network host 

	opts=(
		--cap-add NET_ADMIN
		--cap-add SYS_ADMIN
		--cap-add SYS_PTRACE
		--security-opt seccomp=unconfined
		--security-opt apparmor=unconfined)
	sec_opts="${opts[*]}"

	opts=(
		--device /dev/net/tun
		--device /dev/fuse)
	dev_opts="${opts[*]}"

	opts=(
		-v /home/${HOST_USER}:/h
		-v /v:/v
		-v /var/run/docker.sock:/var/run/docker.sock)
	vol_opts="${opts[*]}"
	
	echo "# docker run ..."
	runn docker run -d -it --rm \
		--name $BOX_NAME \
		--cidfile $var_run/$BOX_NAME.cid \
		-e DEVKA_BUILD=1 \
		-m $RAM \
		-u root \
		\
		$sec_opts \
		$dev_opts \
		$vol_opts \
		\
		$BOX_IMAGE

	echo "# setup-user ..."
	$OP docker cp $HERE/setup-user $BOX_DNAME:/tmp/setup-user
	$OP docker exec -it \
		-e DEVKA_BUILD=1 \
		-e HOST_USER=${HOST_USER} \
		-e HOST_GROUP=${HOST_GROUP} \
		-e HOST_UID=${HOST_UID} \
		-e HOST_GID=${HOST_GID} \
		-u root \
		$BOX_DNAME bash -c /tmp/setup-user

	echo "# setup-as-user ..."
	$OP docker cp $HERE/setup-as-user $BOX_DNAME:/tmp/setup-as-user
	$OP docker exec -it \
		-e GIT_USER_NAME="${GIT_USER_NAME}" \
		-e GIT_EMAIL="${GIT_EMAIL}" \
		-u $HOST_USER \
		$BOX_NAME bash -l -c /tmp/setup-as-user

	echo "# Done."
	if [[ -z $_Dbg_DEBUGGER_LEVEL ]]; then
		trap - ERR
	fi
fi

$OP docker exec -it \
	-e DEVBOX="$BOX_NAME" -e DEVBOX_NAME="$BOX_NAME" -e DOCKER_NAME="$BOX_NAME" \
	-e _DEVBOX_UPDATE=1 \
	-u $HOST_USER \
	$BOX_NAME bash -l
