#!/usr/bin/env bash

echo "# start setup-user ..."

#----------------------------------------------------------------------------------------------

is_command() {
	command -v $1 &> /dev/null
}

xinstall() {
	local packs="$@"

	if is_command apt-get; then
		export DEBIAN_FRONTEND=noninteractive
		$SUDO apt-get update -qq
		$SUDO apt-get install --fix-missing -y $packs
	elif is_command dnf; then
		$SUDO dnf install -y $packs
	elif is_command tdnf; then # mariner linux
		$SUDO tdnf install -y $packs
		$SUDO yum install -y $packs
	elif is_command zypper; then
		$SUDO zypper install -y $packs
	elif is_command apk; then
		$SUDO apk update
		$SUDO apk add $packs
	elif is_command pacman; then
		$SUDO pacman --noprogressbar -Sy
		$SUDO pacman --noconfirm --noprogressbar -S $packs
	elif is_command brew; then
		for p in $packs; do
			brew list $p &>/dev/null || brew install $p
		done
	elif is_command pkg; then
		$SUDO pkg install -y $packs
	fi
}

fatal() {
	>&2 echo "$@"
	exit 1
}

[[ $NOP == 1 ]] && OP=echo

#----------------------------------------------------------------------------------------------

# this will create user `user` with id 1000 and homedir /home/.user
# if a user named `user` exists (its id may not be 1000), it is removed
# also, if user with id 1000 exists, it is removed
# the home directory of user 1000 exists, it is renamed to /home/.user

build_phase() {
	local USER_ID=1000
	local USER=user
	local HOME_DIR=/home/.user

	local old_user="$(id -nu $USER_ID 2> /dev/null)"
	if [[ -n $old_user ]]; then
		$OP userdel $old_user
		$OP rm -f /etc/sudoers.d/$old_user
		if [[ -d /home/$old_user ]]; then
			$OP mv /home/$old_user $HOME_DIR
		fi
	fi
	if id $USER >& /dev/null; then
		$OP userdel $USER
		$OP rm -f /etc/sudoers.d/$USER
	fi

	$OP useradd -u $USER_ID -U -m -d $HOME_DIR -s /bin/bash $USER
	if [[ $NOP != 1 ]]; then
		echo root:password ${USER}:password | chpasswd
	else
		echo "echo root:password ${USER}:password | chpasswd"
	fi

	mkdir -p /etc/sudoers.d
	if [[ $NOP != 1 ]]; then
		echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER
	else
		echo "\"$USER ALL=(ALL) NOPASSWD: ALL\" > /etc/sudoers.d/$USER"
	fi
	$OP chown -R $USER_ID $HOME_DIR

	if ! is_command sudo; then
		SUDO="" $OP xinstall sudo
	fi
}

#----------------------------------------------------------------------------------------------

[[ $(id -un) != root ]] && fatal "should run as root"

if [[ ! -d /home/.user ]]; then
	echo "# build phase ..."
	build_phase
	exit 0
fi

#----------------------------------------------------------------------------------------------

echo "# start phase ..."

[[ -z $HOST_USER ]] && fatal "HOST_USER is not defined"
[[ -z $HOST_UID || -z $HOST_GID ]] && fatal "HOST_UID or HOST_GID are not defined"
if [[ -n $HOST_GID ]]; then
	[[ -z $HOST_GROUP ]] && fatal "HOST_GROUP is not defined"
fi

USER="$HOST_USER"

cat <<-END >> /etc/fstab
	/home/.user /home/$USER none bind 0 0
	END
mkdir -p /home/$USER
chown $HOST_UID:$HOST_GID /home/$USER
mount -a

old_user="$(id -nu $HOST_UID 2> /dev/null)"
if [[ $? == 0 ]]; then
	$OP userdel $old_user
	$OP rm -f /etc/sudoers.d/$old_user
fi

if [[ -n $HOST_GID ]]; then
	if ! getent group $HOST_GID &> /dev/null; then
		$OP groupadd -g $HOST_GID $HOST_GROUP
	fi
	gopt="-g $HOST_GID"
else
	gopt="-U"
fi

$OP useradd -u $HOST_UID $gopt -m -d /home/$USER -s /bin/bash $USER
if [[ $NOP != 1 ]]; then
	echo root:password ${USER}:password | chpasswd
else
	echo "echo root:password ${USER}:password | chpasswd"
fi

if [[ $NOP != 1 ]]; then
	echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER
else
	echo "echo \"$USER ALL=(ALL) NOPASSWD: ALL\" > /etc/sudoers.d/$USER"
fi

if [[ $HOST_UID != 1000 && $HOST_GID != 1000 ]]; then
	echo "# chown -R $HOST_UID:$HOST_GID /home/$USER"
	$OP chown -R $HOST_UID:$HOST_GID /home/.user
fi

chmod r+g /home/.user
