#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
CLASSICO="$(cd $HERE/../classico && pwd)"
. $CLASSICO/shibumi/defs

[[ $($CLASSICO/bin/iscontainer) != 1 ]] && fatal "should run within devbox container"
[[ $(id -un) != root ]] && fatal "should run as root"
[[ -z $BOX_USER ]] && fatal "BOX_USER is not defined"
[[ -z $HOST_UID || -z $HOST_GID ]] && fatal "HOST_UID or HOST_GID are not defined"

USER="$BOX_USER"
USER_HOME="/home/$USER"

if [[ ! -d $USER_HOME ]]; then
	groupadd -g $HOST_GID $USER
	useradd -u $HOST_UID -g $HOST_GID -s /bin/bash -m $USER
	echo root:password ${USER}:password | chpasswd
fi

# sed -i "/root.*ALL/a $USER ALL=(ALL:ALL) NOPASSWD:ALL" /etc/sudoers
echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER

cd $USER_HOME

mv $HOME/.user-setup/.devka .
mv $HOME/.user-setup/.devka-user .

chown -R $USER:$USER .devka .devka-user
