#!/usr/bin/env python

import sys
import os
import argparse

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
CLASSICO = os.path.join(ROOT, "classico")
sys.path.insert(0, CLASSICO)
import paella

#----------------------------------------------------------------------------------------------

class SystemSetup(paella.Setup):
    def __init__(self, args):
        paella.Setup.__init__(self, args.nop)

    def common_first(self):
        if self.os != 'windows':
            self.install("jq")
        if not self.platform.is_redhat_compat():
            self.install("moreutils")

        self.run("getgcc")
        if self.osnick != "arch":
            self.run("getgit --modern")

    def linux_first(self):
        self.install("bridge-utils nmap iptables")
        self.install("psmisc htop btop")
        self.install("vim mc tmux ripgrep jq")
        self.install("tig git-delta")

    def debian_compat(self):
        self.install("iputils-ping iproute2")

    def archlinux(self):
        self.run("getgit")
        self.install("iputils iproute2")

    def redhat_compat(self):
        self.install("iputils iproute")

    def fedora(self):
        self.install("iputils iproute")

    def linux_last(self):
        pass

    def common_last(self):
        self.run("getbashdb")
        self.run("getpudb")
        self.run("getclang --format")
        self.run("getrust")
        self.run("getcmake --usr")
        self.run("getgdb --modern")

#----------------------------------------------------------------------------------------------

parser = argparse.ArgumentParser(description='Set up system for build.')
parser.add_argument('-n', '--nop', action="store_true", help='no operation')
args = parser.parse_args()

SystemSetup(args).setup()
