#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
CLASSICO="$(cd $HERE/.. && pwd)"
. $CLASSICO/shibumi/defs

OP=""
[[ $NOP == 1 ]] && OP=echo

cd $HOME

$OP mkdir -p views
$OP sudo ln -sf /v $HOME/views

runn $HERE/setup-host-cfg
runn $CLASSICO/devbox/setup
