#!/usr/bin/env python

import sys
import os
import argparse

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
CLASSICO = os.path.join(ROOT, "classico")
sys.path.insert(0, CLASSICO)
import paella

#----------------------------------------------------------------------------------------------

class SystemSetup(paella.Setup):
    def __init__(self, args):
        paella.Setup.__init__(self, args.nop)

    def common_first(self):
        if self.os != 'windows':
            self.install("jq")
        if not self.platform.is_redhat_compat():
            self.install("moreutils")

        self.run(f"{CLASSICO}/bin/getgcc")
        self.run(f"{CLASSICO}/bin/getgit --modern")

    def linux_first(self):
        self.install("bridge-utils nmap iptables")
        self.install("psmisc htop btop")
        self.install("vim mc tmux ripgrep jq")
        self.install("tig git-delta")

    def debian_compat(self):
        self.install("iputils-ping iproute2")

    def archlinux(self):
        self.install("iputils iproute2")

    def redhat_compat(self):
        self.install("iputils iproute")

    def fedora(self):
        self.install("iputils iproute")

    def linux_last(self):
        pass

    def common_last(self):
        self.run(f"{CLASSICO}/bin/getbashdb")
        self.run(f"{CLASSICO}/bin/getpudb")
        self.run(f"{CLASSICO}/bin/getclang --format")
        self.run(f"{CLASSICO}/bin/getrust")
        self.run(f"{CLASSICO}/bin/getcmake --usr")
        self.run(f"{CLASSICO}/bin/getgdb --modern")

#----------------------------------------------------------------------------------------------

parser = argparse.ArgumentParser(description='Set up system for build.')
parser.add_argument('-n', '--nop', action="store_true", help='no operation')
# parser.add_argument('--bool', action="store_true", help="flag")
# parser.add_argument('--int', type=int, default=1, help='number')
# parser.add_argument('--str', type=str, default='str', help='string')
# parser.add_argument("--mode", choices=["fast", "slow", "medium"], default="medium")
# parser.add_argument("--summary", choices=["short", "long"], nargs="?", const="short")  # None if not present
args = parser.parse_args()

SystemSetup(args).setup()
