#!/usr/bin/env bash

PROGRAM="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

if  [[ $FORCE != 1 ]]; then
	exit
fi

if [[ -f ~/.devka/bin/devka.sh ]]; then
	sed -i '1i\return' ~/.devka/bin/devka.sh
fi

cat <<-'END' > /tmp/remove-devka
	#!/usr/bin/env bash

	rm -rf ~/.devka ~/.devka-user ~/.bun ~/.fnm ~/.jasmine ~/.local/bin ~/.local/opt ~/.npm ~/.profile.d ~/.venv
	sed -i '/devka/d' ~/.bash_profile
	sed -i '/devka/d' ~/.bashrc
	sudo sed -i '/devka/d' /etc/profile
	sudo sed -i '/devka/d' /etc/bash.bashrc
	END
chmod +x /tmp/remove-devka
exec /tmp/remove-devka
