#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)

# classsico will place read_profile_d logic in .bash_profile
# it will be used during installation and then removed as dekva will handle it
touch $HOME/.bash_profile
cp $HOME/.bash_profile $HOME/.bash_profile.keep
export CLASSICO=$ROOT/classico
. $CLASSICO/shibumi/defs

install_devka() {
	$CLASSICO/sbin/setup
	AUTO=0 $CLASSICO/bin/getstarship

	mv $HOME/.bash_profile.keep $HOME/.bash_profile

	for f in ~/.bashrc ~/.bash_profile; do
		if ! grep devka $f >& /dev/null; then
			printf '\n%s\n' '. $HOME/.devka/bin/devka.sh' >> $f
		fi
	done
	cp $HOME/.bash_profile $HOME/.bash_profile.new

	for f in /etc/bash.bashrc /etc/profile; do
		if ! grep devka $f >& /dev/null; then
			printf '\n%s\n' ". $HOME/.devka/bin/devka.sh" | $SUDO tee -a $f > /dev/null
		fi
	done

	local devka_sudoers="$(mktemp /tmp/devka-XXXXXX)"
	cat <<-END > $devka_sudoers
		Defaults env_keep += "ENVENIDO FNM_ENV_FILE"
		END
	$SUDO chown root:root $devka_sudoers
	$SUDO cp $devka_sudoers /etc/sudoers.d/devka
}

$SUDO true

echo "Installing Devka ..."
if (( V > 0 )); then
	install_devka
else
	spin_while install_devka
fi

